create table monitor (
    rowid       integer primary key,
    date_time   integer,
    cpu_usr     integer,
    cpu_sys     integer,
    cpu_tot     integer,
    mem_usd     integer,
    mem_tot     integer,
    swp_usd     integer,
    swp_tot     integer,
    dsk_0b_rop  integer,
    dsk_0b_wop  integer,
    dsk_0b_rmb  integer,
    dsk_0b_wmb  integer,
    dsk_0b_rtm  integer,
    dsk_0b_wtm  integer,
    dsk_0c_rop  integer,
    dsk_0c_wop  integer,
    dsk_0c_rmb  integer,
    dsk_0c_wmb  integer,
    dsk_0c_rtm  integer,
    dsk_0c_wtm  integer,
    net_smb     integer,
    net_rmb     integer,
    db1_ses     integer
);
